export const ErrorCodes = {
  // Decks
  DECK_NOT_FOUND: 'DECK_NOT_FOUND',
  DECK_FORBIDDEN: 'DECK_FORBIDDEN',
  DECK_CANNOT_UPDATE_SYSTEM: 'DECK_CANNOT_UPDATE_SYSTEM',
  DECK_CANNOT_DELETE_FAVORITES: 'DECK_CANNOT_DELETE_FAVORITES',
  FAVORITES_DECK_NOT_FOUND: 'FAVORITES_DECK_NOT_FOUND',
  DECK_NAME_DUPLICATE: 'DECK_NAME_DUPLICATE',
  LEARNING_LEVEL_NOT_FOUND: 'LEARNING_LEVEL_NOT_FOUND',
  FAVORITES_DECK_LEVEL_FORBIDDEN: 'FAVORITES_DECK_LEVEL_FORBIDDEN',

  // Vocabularies
  VOCABULARY_NOT_FOUND: 'VOCABULARY_NOT_FOUND',
  VOCABULARY_FORBIDDEN: 'VOCABULARY_FORBIDDEN',
  DUPLICATE_VOCABULARY: 'DUPLICATE_VOCABULARY',
  WORD_EXISTS_WITH_DIFFERENT_MEANING: 'WORD_EXISTS_WITH_DIFFERENT_MEANING',
  FAVORITES_DECK_MANUAL_EDIT_FORBIDDEN: 'FAVORITES_DECK_MANUAL_EDIT_FORBIDDEN',
  SYSTEM_DECK_VOCAB_EDIT_FORBIDDEN: 'SYSTEM_DECK_VOCAB_EDIT_FORBIDDEN',

  // Favorites
  FAVORITE_COPY_NOT_FOUND: 'FAVORITE_COPY_NOT_FOUND',

  // Imports
  IMPORT_FILE_REQUIRED: 'IMPORT_FILE_REQUIRED',
  IMPORT_INVALID_CSV: 'IMPORT_INVALID_CSV',
  IMPORT_FAVORITES_FORBIDDEN: 'IMPORT_FAVORITES_FORBIDDEN',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

